### ISSUE TITLE
Support for 27chan.org

### ISSUE THREAD

**Issue by 4lch3-m1st** [Mishiranu/Dashchan-Extensions#12]
I managed to create an extension supporting 27chan.org. It is a direct fork from lainchan's.
I'd humbly like to ask you to create a branch for it, so I can pull request, or even copy the code from my repo, I don't really care about that. And, of course, to release it.

Link to the fork: https://github.com/4lch3-m1st/Dashchan-Extensions/tree/twentyseven

**Comment by Mishiranu** [comment]
Great, thanks!
I don't know whether it's possible to make a pull request to non-existing branch so I'll create it myself.
Do you mind if I add you to the LICENSE file?

**Comment by 4lch3-m1st** [comment]
Not at all! Please do.

**Comment by Mishiranu** [comment]
https://raw.githubusercontent.com/Mishiranu/Dashchan-Extensions/master/update/package/DashchanTwentySeven.apk

Ready!
