### ISSUE TITLE
I've written an extension, how can I get it merged?

### ISSUE THREAD

**Issue by nilesr** [Mishiranu/Dashchan-Extensions#16]
The extension is [here](https://github.com/dangeru/Dashchan-Extension), and it implements the API that's been documented [here](https://github.com/dangeru/awoo-API)

I've tested it on my phone and an emulator, and given out the initial release to a few other people to test, and other than a few small things it's good to go. However, github won't let me make a pull request because it's not a fork of this repository.

Can I just give you a diff? Should I fork Dashchan-Extensions/fourchan again and rebase my changes, then make a new pull request?

Thanks in advance

**Comment by Mishiranu** [comment]
Thanks for your work.

Right now I'm a bit busy but later I will test your extension and then add it as a separate branch if everything is OK.

**Comment by Mishiranu** [comment]
So I checked and made some changes: https://github.com/Mishiranu/Dashchan-Extensions/tree/awoo

(I prefer to use tabs instead of spaces in my projects.)

Also I implemented markup, HTML parser for boards and fixed some minor issues.

The only thing left is icon. I don't know which icon should I use. 4chan icon definitely doesn't fit.

Also new release will have version code 1.0. It's not a big problem because users anyway will have to reinstall the app due to signature change.

**Comment by nilesr** [comment]
Thank you so much for your help, I didn't find out about markup, newlines etc being broken until after I had sent it off to you.

Either of these icons would work well if you want to add them  
https://github.com/nilesr/United4/blob/master/app/src/main/res/raw/normal_dangeru.png  
https://github.com/nilesr/United4/blob/master/app/src/main/res/mipmap/ic_launcher_real.png

I'll let you know if I see any other problems or need help with something else, thanks again for everything

**Comment by Mishiranu** [comment]
The second icon is too complex, I don't think it will look good because it's very small in app.

I can try to adapt the first option.

**Comment by Mishiranu** [comment]
Sorry, I completely forgot about you.

I updated the icon and renamed classes again (I missed something, extension name is actually `dangeru`, not `awoo`). Also I moved the code to `dangeru` branch.

[APK](https://github.com/Mishiranu/Dashchan-Extensions/raw/master/update/package/DashchanDangeru.apk) (included to README.md in main repo).

**Comment by nilesr** [comment]
No problem, thanks so much for all your help
