### ISSUE TITLE
New extension: moechannel (2channel.moe)

### ISSUE THREAD

**Issue by tsunamaru** [Mishiranu/Dashchan-Extensions#25]
Некоторое время назад кто-то из посетителей [2channel.moe](https://2channel.moe) написал для него модуль, используя базу от расширения двача. Позже он [выложил](https://2channel.moe/b/res/77866.html#121610) diff со своими изменениями.  
Я форкнул https://github.com/Mishiranu/Dashchan-Extensions/commit/1a5d9fb100971cbeea964707d1d4d8b8be327429 и применил дифф в новой ветке [moechannel](https://github.com/tsunamaru/Dashchan-Extensions/tree/moechannel), отредактировав от себя только README.md  

Как теперь отправить пулл реквест в этот репозиторий? Гитхаб не даёт мне указать новый бранч, а официальная документация гласит, что для этого мне нужны права на запись в аппстрим.  

PS: спасибо, что живой!

**Comment by Mishiranu** [comment]
Вообще можно отправить пуллреквест в существующую ветку (уже есть три открытых), но не уверен, можно ли таким образом создать новую ветку.

Вообще мне бы хотелось, чтобы другие люди занимались расширениями, мне как-то поднадоело их делать уже, и я сам вряд ли какие-то новые делать буду в ближайшее время.

Я вообще планирую немного реконструировать стуктуру хранения и сборки модулей у себя в проекте. Возможно, в ближайшее время даже.

А вообще было бы хорошо, если подобные модули люди сами делали и выкладывали. Если прописать в модуле адрес для обновления, то модуль будет знать, откуда себя скачивать, и будет уметь обновляться как и любой другой, даже когда его нет в репозитории. Мне вот, честно, прямо сейчас очень лениво заниматься ревью модуля и какими-то его правками.

**Comment by tsunamaru** [comment]
Понял. А из-за чего может возникать после установки модуля диалог ```Allow this extension to manage application...```?

**Comment by Mishiranu** [comment]
Если бы я не спрашивал, любое бы вредоносное ПО могло бы подгрузиться как модуль дашчана и иметь все привилегии, что и сам дашчан, а их немало.
Не спрашивает только для модулей, которые подписаны тем же ключём, что и сам клиент. Т.е. клиент не спрашивает для моих сборок разрешения для собранных мной же модулей.

**Comment by Mishiranu** [comment]
В итоге переписал с нуля, потому что и для 2ch.hk расширение очень сильно изменилось с тех пор. Позабавило, конечно, насколько сильно сайт и апи похож на 2ch.hk, поэтому было совсем несложно.

**Comment by tsunamaru** [comment]
Вот это спасибо! А функционал редактирования своего поста можешь прикрутить?

**Comment by Mishiranu** [comment]
Редактирование будет сложно сделать, клиент это не поддерживает. В общем случае, разные борды позволяют редактировать лишь отдельные поля, да и в UI надо продумывать, как это сделать вообще. Сейчас не буду таким заниматься.
