### ISSUE TITLE
Проблемы с reCAPTCHA 2.0

### ISSUE THREAD

**Issue by hey-red** [Mishiranu/Dashchan-Extensions#4]
Не знаю относится ли это к работе с рекапчей в самом дашчане или проблема модуля(horochan). 
При запросе капчи все ок, выбираю изображения, жму ОК и через некоторое время всплывает "Ошибка при загрузке данных" т.е до отправки поста дело не доходит.
Подебажить на устройстве пока не могу, но если поможет оно на ведре 4.1.1
Да и еще. В API хорочана теперь есть значение `captchaEnabled: bool` которое присутствует в /boards и /threads

**Comment by Mishiranu** [comment]
С капчей известная проблема, она была исправлена в одном из коммитов, но я ту версию ещё не релизил (я очень давно клиент не обновлял, потому что есть ещё важные дела, которые надо сделать перед апдейтом). Пока что можно отключить использование Javascript в настройках, тогда капча будет работать, но она будет сложнее. https://github.com/Mishiranu/Dashchan/issues/108

А вот про поле конфига я не знал, надо будет добавить.

**Comment by Mishiranu** [comment]
А есть возможность сделать так, чтобы узнать информацию о включённой капче на загружая заново весь тред?

**Comment by hey-red** [comment]
@Mishiranu Например? Вывести этот параметр в часть отвечающую за подгрузку постов?

**Comment by Mishiranu** [comment]
Ну можно, наверное, если возможно будет использовать это в таком виде:
`https://api.horochan.ru/v1/threads/10000/after/999999999`

**Comment by hey-red** [comment]
@Mishiranu да, уже сделал.

**Comment by Mishiranu** [comment]
Хорошо. Обновил расширение.
